###  
GET http://localhost:8080/ 
Accept: application/json   
### GET ALL DATA 
GET http://localhost:8080/actors 
Accept: application/json  
### GET ONE DATA 
GET http://localhost:8080/languages/1 Accept: application/json